# Generated by Django 6.0 on 2026-01-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="uservisit",
            index=models.Index(
                fields=["timestamp"], name="analytics_u_timesta_cbf9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uservisit",
            index=models.Index(
                fields=["session_key", "timestamp"],
                name="analytics_u_session_856179_idx",
            ),
        ),
    ]
