# Generated by Django 6.0 on 2026-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., AE, IN, SA)",
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        help_text="International phone code (e.g., +971, +91, +966)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED",
                        help_text="Currency code (e.g., AED, INR, SAR)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="countries_c_code_79f189_idx")
                ],
            },
        ),
    ]
