# Generated by Django 6.0 on 2026-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VERIFICATION_APPROVED", "Verification Approved"),
                            ("VERIFICATION_REJECTED", "Verification Rejected"),
                            ("VERIFICATION_PENDING", "Verification Pending"),
                            ("PAYMENT_SUCCESS", "Payment Successful"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PROPERTY_APPROVED", "Property Approved"),
                            ("PROPERTY_REJECTED", "Property Rejected"),
                            ("PROPERTY_EXPIRED", "Property Expired"),
                            ("GYM_APPROVED", "Gym Approved"),
                            ("GYM_REJECTED", "Gym Rejected"),
                            ("GYM_EXPIRED", "Gym Expired"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
