# Generated by Django 6.0 on 2026-01-26 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        help_text="Firebase Cloud Messaging token for the device",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        help_text="Type of device",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device name/identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this device was active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Device",
                "verbose_name_plural": "User Devices",
                "ordering": ["-last_active"],
                "indexes": [
                    models.Index(
                        fields=["user", "fcm_token"],
                        name="notificatio_user_id_36edfe_idx",
                    ),
                    models.Index(
                        fields=["fcm_token"], name="notificatio_fcm_tok_1ca75b_idx"
                    ),
                ],
            },
        ),
    ]
