# Generated by Django 6.0 on 2026-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_userdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("VERIFICATION_APPROVED", "Verification Approved"),
                    ("VERIFICATION_REJECTED", "Verification Rejected"),
                    ("VERIFICATION_PENDING", "Verification Pending"),
                    ("PAYMENT_SUCCESS", "Payment Successful"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("PROPERTY_APPROVED", "Property Approved"),
                    ("PROPERTY_REJECTED", "Property Rejected"),
                    ("PROPERTY_EXPIRED", "Property Expired"),
                    ("PROPERTY_SOLD", "Property Sold"),
                    ("GYM_APPROVED", "Gym Approved"),
                    ("GYM_REJECTED", "Gym Rejected"),
                    ("GYM_EXPIRED", "Gym Expired"),
                    ("NEW_OWNER_REGISTERED", "New Owner Registered"),
                    ("NEW_GYM_OWNER_REGISTERED", "New Gym Owner Registered"),
                    ("NEW_PROPERTY_CREATED", "New Property Created"),
                    ("NEW_GYM_CREATED", "New Gym Created"),
                ],
                max_length=50,
            ),
        ),
    ]
