# Generated by Django 6.0 on 2026-01-24 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardModule",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Unique identifier for the module (e.g., 'fitness', 'gyms')",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Module name (e.g., 'fitness', 'gyms')",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., 'My Fitness', 'Gyms')",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name (e.g., 'dumbbell', 'home')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Frontend route path (e.g., '/admin/fitness')",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this module is active and visible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent module (null for top-level modules)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dashboard.dashboardmodule",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Required permissions to access this module",
                        related_name="modules",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Module",
                "verbose_name_plural": "Dashboard Modules",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["parent", "is_active"],
                        name="dashboard_d_parent__7df4f8_idx",
                    ),
                    models.Index(fields=["order"], name="dashboard_d_order_ca5db6_idx"),
                ],
            },
        ),
    ]
