# Generated by Django 6.0 on 2026-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(
                blank=True, help_text="Website URL", max_length=500, null=True
            ),
        ),
    ]
