# Generated by Django 6.0 on 2026-01-24 06:50

import apps.ads.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("brand_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="ads/logos/",
                        validators=[
                            apps.ads.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location description, e.g., 'Downtown Dubai, UAE'",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number for contact",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the video for the ad",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the image for the ad",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "available_units",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                            ("yearly", "Yearly"),
                            ("daily", "Daily"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the ad was approved and published",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["verification_status"], name="ads_ad_verific_5e696e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to="ads/gallery/",
                        validators=[
                            apps.ads.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="ads.ad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Gallery",
                "verbose_name_plural": "Ad Galleries",
                "ordering": ["-created_at"],
            },
        ),
    ]
