# Generated by Django 6.0 on 2026-01-24 06:50

import apps.real_estate.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompletionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Completion Status",
                "verbose_name_plural": "Completion Statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FurnishingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Furnishing Status",
                "verbose_name_plural": "Furnishing Statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OccupantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Occupant Type",
                "verbose_name_plural": "Occupant Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_id",
                    models.IntegerField(
                        help_text="Original Property ID before archiving"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "property_type_name",
                    models.CharField(
                        help_text="Stored as string for archive", max_length=200
                    ),
                ),
                (
                    "purpose_name",
                    models.CharField(
                        help_text="Stored as string for archive", max_length=200
                    ),
                ),
                (
                    "furnishing_status_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("completion_status_name", models.CharField(max_length=200)),
                (
                    "occupant_type_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField()),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "floor_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("unit_number", models.CharField(blank=True, max_length=50, null=True)),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                ("location_latitude", models.FloatField(blank=True, null=True)),
                ("location_longitude", models.FloatField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("occupants_count", models.PositiveIntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rent_period", models.CharField(blank=True, max_length=20, null=True)),
                ("handover_date", models.DateField(blank=True, null=True)),
                (
                    "developer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amenities",
                    models.JSONField(default=list, help_text="List of amenity names"),
                ),
                (
                    "main_image_url",
                    models.TextField(
                        blank=True, help_text="Original URL before deletion", null=True
                    ),
                ),
                ("social_media", models.JSONField(blank=True, default=dict)),
                (
                    "owner_info",
                    models.JSONField(
                        default=dict,
                        help_text="Owner information: id, email, name, etc.",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "listing_status",
                    models.CharField(default="OFF_MARKET", max_length=20),
                ),
                ("rejection_note", models.TextField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(help_text="Original creation date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(help_text="Last update date before archiving"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(help_text="When property was soft deleted"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When property was moved to archive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived Property",
                "verbose_name_plural": "Archived Properties",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[("call", "Call"), ("whatsapp", "WhatsApp")],
                        help_text="Method of contact: call or whatsapp",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Property Contact",
                "verbose_name_plural": "Property Contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="properties/gallery/",
                        validators=[
                            apps.real_estate.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Property Gallery",
                "verbose_name_plural": "Property Galleries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("occupant_count", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Property Type",
                "verbose_name_plural": "Property Types",
                "ordering": ["asset_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Purpose",
                "verbose_name_plural": "Purposes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "floor_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("unit_number", models.CharField(blank=True, max_length=50, null=True)),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="Nationality of the property owner",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "occupants_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of occupants allowed (e.g., 2, 3, 4)",
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rent_period",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("handover_date", models.DateField(blank=True, null=True)),
                (
                    "developer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="properties/main/",
                        validators=[
                            apps.real_estate.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("social_media", models.JSONField(blank=True, default=dict)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin approval status - separate from subscription status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether property is active and visible. Auto-managed based on subscription status.",
                    ),
                ),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("SOLD", "Sold"),
                            ("RENTED", "Rented"),
                            ("OFF_MARKET", "Temporarily Off Market"),
                        ],
                        default="OFF_MARKET",
                        help_text="Market availability status. Automatically set to AVAILABLE when approved, OFF_MARKET when not approved.",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_note",
                    models.TextField(
                        blank=True,
                        help_text="Note provided by admin when rejecting property",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - property is marked as deleted but not permanently removed",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when property was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Property expiration date. Set when admin approves the property. Property becomes inactive after this date.",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when property was approved by admin. Used to calculate expiration.",
                        null=True,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="properties", to="real_estate.amenity"
                    ),
                ),
                (
                    "completion_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="real_estate.completionstatus",
                    ),
                ),
                (
                    "furnishing_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="real_estate.furnishingstatus",
                    ),
                ),
                (
                    "occupant_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of occupant suitable for this property: Bachelor, Family, etc.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="real_estate.occupanttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
    ]
