# Generated by Django 6.0 on 2026-01-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("real_estate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="propertyarchive",
            index=models.Index(
                fields=["original_id"], name="real_estate_origina_feba65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyarchive",
            index=models.Index(
                fields=["archived_at"], name="real_estate_archive_49aa9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyarchive",
            index=models.Index(
                fields=["deleted_at"], name="real_estate_deleted_87b456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyarchive",
            index=models.Index(
                fields=["owner_info"], name="real_estate_owner_i_c40669_idx"
            ),
        ),
        migrations.AddField(
            model_name="propertycontact",
            name="property",
            field=models.ForeignKey(
                help_text="The property the seeker is interested in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_requests",
                to="real_estate.property",
            ),
        ),
        migrations.AddField(
            model_name="propertycontact",
            name="seeker",
            field=models.ForeignKey(
                help_text="The user (seeker/buyer) who is contacting the owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertygallery",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="real_estate.property",
            ),
        ),
        migrations.AddField(
            model_name="propertytype",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_types",
                to="real_estate.assettype",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="real_estate.propertytype",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="real_estate.purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="propertycontact",
            index=models.Index(
                fields=["property", "created_at"], name="real_estate_propert_86b2e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertycontact",
            index=models.Index(
                fields=["seeker", "created_at"], name="real_estate_seeker__cd32b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertytype",
            unique_together={("asset_type", "name")},
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "purpose"],
                name="real_estate_propert_fcf34d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="real_estate_price_d2712e_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_active", "is_approved"],
                name="real_estate_is_acti_c4ff4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["listing_status", "is_approved"],
                name="real_estate_listing_d0dfe6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_deleted", "deleted_at"],
                name="real_estate_is_dele_197a46_idx",
            ),
        ),
    ]
