# Generated by Django 6.0 on 2026-01-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="rent_period",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
