# Generated by Django 6.0 on 2026-01-24 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "property_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Property ID this payment is for",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "individual_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Charge amount per property for INDIVIDUAL sellers (AED)",
                        max_digits=10,
                    ),
                ),
                (
                    "company_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Subscription charge amount for COMPANY sellers (AED)",
                        max_digits=10,
                    ),
                ),
                (
                    "company_subscription_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Subscription validity in days for COMPANY sellers (default: 90 days = 3 months)",
                    ),
                ),
                (
                    "agent_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Subscription charge amount for AGENT sellers (AED)",
                        max_digits=10,
                    ),
                ),
                (
                    "agent_subscription_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Subscription validity in days for AGENT sellers (default: 90 days = 3 months)",
                    ),
                ),
                (
                    "advertiser_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Charge amount for ADVERTISER sellers (AED)",
                        max_digits=10,
                    ),
                ),
                (
                    "advertiser_subscription_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Subscription validity in days for ADVERTISER sellers (default: 90 days = 3 months)",
                    ),
                ),
                (
                    "advertisement_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Charge amount per advertisement (AED)",
                        max_digits=10,
                    ),
                ),
                (
                    "advertisement_validity_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Advertisement validity in days (default: 30 days = 1 month)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED",
                        help_text="Default currency for all charges",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is active. Only one active configuration should exist.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Configuration",
                "verbose_name_plural": "Payment Configurations",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("stripe_event_type", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AED", max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID (for wallet redemption flow)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of listings posted so far"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False,
                        help_text="Whether subscription should auto-renew when it expires",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plan name (e.g., 'Basic Individual Plan')",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Seller"),
                            ("seeker", "Buyer"),
                            ("admin", "Admin"),
                            ("gym_owner", "Gym Owner"),
                        ],
                        default="owner",
                        help_text="User role this plan is designed for (e.g., owner, seeker, gym_owner)",
                        max_length=20,
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("AGENT", "Agent"),
                            ("COMPANY", "Company"),
                        ],
                        help_text="Required when role='owner'. One of: INDIVIDUAL / AGENT / COMPANY.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in AED", max_digits=10
                    ),
                ),
                (
                    "is_offer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this plan has an active offer. If True, offer_percentage is required.",
                    ),
                ),
                (
                    "offer_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Offer discount percentage (0-100). Required when is_offer=True. If set, offer_price will be calculated automatically.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Subscription duration in days (required)"
                    ),
                ),
                (
                    "max_listings",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of listings allowed. Leave null for unlimited listings.",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for purchase",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Plan description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["role", "seller_type", "price"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current wallet balance in points",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED",
                        help_text="Currency for wallet balance",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletPointsSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_sale",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Points awarded per property sale (1 Point = 1 AED)",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wallet Points Setting",
                "verbose_name_plural": "Wallet Points Settings",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit"),
                            ("DEBIT", "Debit"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive for credit, negative for debit)",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance before this transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after this transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of reference object (e.g., 'apps.real_estate.models.Property')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of reference object (e.g., Property ID)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Transaction description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
