# Generated by Django 6.0 on 2026-01-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who last updated this configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_payment_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                help_text="One subscription per user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payments.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["role", "seller_type", "is_active"],
                name="payments_su_role_5f7c59_idx",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription plan this subscription is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="payments.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                help_text="User who owns this wallet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="walletpointssetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who last updated this setting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_wallet_points_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this transaction (for admin adjustments)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                help_text="Wallet this transaction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="payments_wa_user_id_cd1a1f_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["balance"], name="payments_wa_balance_faa9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="payments_wa_wallet__9a8a81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="payments_wa_transac_b3760c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="payments_wa_referen_28f832_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["created_by"], name="payments_wa_created_ad7e3c_idx"
            ),
        ),
    ]
