# Generated by Django 6.0 on 2026-01-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="custom_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role for which this offer applies (e.g., owner, gym_owner, seeker)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="users.role",
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["created_at"], name="offers_offe_created_968b40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["custom_role"], name="offers_offe_custom__cdf94a_idx"
            ),
        ),
    ]
