# Generated by Django 6.0 on 2026-01-24 06:50

import apps.fitness.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="facility_icons/",
                        validators=[
                            apps.fitness.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GymImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gyms/gallery/",
                        validators=[
                            apps.fitness.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gym Image",
                "verbose_name_plural": "Gym Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gym_icons/",
                        validators=[
                            apps.fitness.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gym Type",
                "verbose_name_plural": "Gym Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., 'daily', 'weekly', 'monthly', '6 months', 'yearly'",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Includes Free PT Session, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership Package",
                "verbose_name_plural": "Membership Packages",
                "ordering": ["duration"],
            },
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_24_hours", models.BooleanField(default=False)),
                (
                    "off_day",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of days when the gym is closed (e.g., ['Saturday', 'Sunday'])",
                    ),
                ),
                (
                    "gender_allowed",
                    models.CharField(
                        choices=[
                            ("MIXED", "Mixed / Unisex"),
                            ("MALE", "Male Only"),
                            ("FEMALE", "Female Only"),
                        ],
                        default="MIXED",
                        max_length=20,
                    ),
                ),
                ("social_media", models.JSONField(blank=True, default=dict)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gyms/main/",
                        validators=[
                            apps.fitness.models.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether gym is active and visible. Set to True when admin approves the gym. Gym becomes inactive when expires_at is reached.",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin approval status - separate from subscription status",
                    ),
                ),
                (
                    "rejection_note",
                    models.TextField(
                        blank=True,
                        help_text="Note provided by admin when rejecting gym",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Gym expiration date. Set when admin approves the gym. Gym becomes inactive after this date.",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when gym was approved by admin. Used to calculate expiration.",
                        null=True,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, related_name="gyms", to="fitness.facility"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym",
                "verbose_name_plural": "Gyms",
                "ordering": ["-created_at"],
            },
        ),
    ]
