# Generated by Django 6.0 on 2026-01-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fitness", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_gyms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gymimage",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="fitness.gym",
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="gym_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gyms",
                to="fitness.gymtype",
            ),
        ),
        migrations.AddField(
            model_name="membershippackage",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="fitness.gym",
            ),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(
                fields=["gym_type"], name="fitness_gym_gym_typ_18a2b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(
                fields=["is_active", "is_approved"],
                name="fitness_gym_is_acti_ace989_idx",
            ),
        ),
    ]
